# Generated by Django 2.0.7 on 2019-11-10 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('CategoryName', models.CharField(max_length=50)),
                ('CategoryActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ProductCode', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductAvailableQuantity', models.IntegerField()),
                ('ProductActive', models.BooleanField(default=True)),
                ('ProductCategoryID', models.ManyToManyField(to='main.Category')),
            ],
        ),
    ]
